include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

test:
  image: gcc:latest
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq cmake lcov python3-dev python3-pip
    - pip3 install cpplint
    - gcc --version
    - cmake --version
  script:
    - sh check-style.sh
    - mkdir build
    - cd build
    - cmake -D TEST=ON -G "Unix Makefiles" ..
    - make
    - ctest -V
    - sh ../coverage.sh
